name: gsp_llm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy=1.26.4
  - scipy=1.16.1
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - networkx
  - matplotlib=3.9.2
  - seaborn
  - pip:
      - torch==2.5.1
      - torchvision==0.20.1
      - torchaudio==2.5.1
      - transformers==4.56.2
      - accelerate==1.10.1
      - bitsandbytes==0.47.0
      - safetensors==0.6.2
      - tqdm
      - sentencepiece==0.2.0
      - tiktoken==0.9.0
      - datasets==4.0.0
      - einops==0.8.1
      - regex
      - huggingface-hub==0.35.0
